services:
  - type: web
    name: phaser-colyseus-combat-game
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start:prod"
    envVars:
      - key: NODE_ENV
        value: production
